### PR TITLE
Add PropEr tests

### PR DESCRIPTION
**Pull request by gnuvince**
Goal is to get rid of eqc tests

### CODE REVIEW

**Comment by gnuvince** [comment]
If the tests look acceptable (basically just copied and pasted from the old eqc tests), I'll also make a commit removing the eqc tests and the dependencies in rebar before we merge.

**Comment by ratelle** [comment]
@gnuvince are you still using this? I thought this add been superseded by @tokenrove work.

**Comment by gnuvince** [comment]
@ratelle Still used by rtb-gateway, although I see that we're using LP's fork of the repo; sorry for the unwanted PR ;)

**Comment by lpgauth** [comment]
We use it for the global blacklist.

**Pull request closed without merging**
